#!/usr/bin/env python3
"""Render every platform's app icon from the single source artwork.

    python3 scripts/generate-icons.py [--src assets/castcircleicon.jpeg]

Writes (all of these are checked in, so the diff shows what changed):

  ios/Runner/Assets.xcassets/AppIcon.appiconset/     15 sizes, opaque
  ios/Runner/Assets.xcassets/LaunchImage.imageset/   1x/2x/3x
  macos/Runner/Assets.xcassets/AppIcon.appiconset/   7 sizes, rounded + alpha
  android/app/src/main/res/mipmap-*/                 legacy + round + adaptive layers
  android/app/src/main/res/mipmap-anydpi-v26/        adaptive-icon XML
  fastlane/metadata/android/en-US/images/            Play icon + feature graphic

Platform rules this encodes, each of which is a rejection or a visual bug if
broken:

  * iOS icons must be OPAQUE — an alpha channel fails App Store validation,
    and iOS applies its own corner mask, so the art is full-bleed square.
  * Play's 512x512 icon must also be opaque (alpha is rejected at upload).
  * macOS does NOT mask its icons: the rounded rect and its margin are part
    of the artwork, per Apple's grid (824pt body inside a 1024pt canvas).
  * Android adaptive layers are 108dp with only the centre 72dp guaranteed
    visible; the launcher's mask crops the rest. The art is therefore scaled
    so its circular composition lands inside that safe zone, and feathered
    into a blurred copy of itself so no square edge shows through a mask.
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Fraction of the source width occupied by the circular composition. Used to
# fit the art inside Android's adaptive-icon safe zone.
ART_EXTENT = 0.86

IOS_ICONS = {
    'Icon-App-20x20@1x.png': 20, 'Icon-App-20x20@2x.png': 40,
    'Icon-App-20x20@3x.png': 60, 'Icon-App-29x29@1x.png': 29,
    'Icon-App-29x29@2x.png': 58, 'Icon-App-29x29@3x.png': 87,
    'Icon-App-40x40@1x.png': 40, 'Icon-App-40x40@2x.png': 80,
    'Icon-App-40x40@3x.png': 120, 'Icon-App-60x60@2x.png': 120,
    'Icon-App-60x60@3x.png': 180, 'Icon-App-76x76@1x.png': 76,
    'Icon-App-76x76@2x.png': 152, 'Icon-App-83.5x83.5@2x.png': 167,
    'Icon-App-1024x1024@1x.png': 1024,
}

MACOS_ICONS = [16, 32, 64, 128, 256, 512, 1024]

# Legacy launcher icon (pre-API-26 and as the fallback everywhere else).
ANDROID_LEGACY = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}
# Adaptive layers are 108dp square at each density.
ANDROID_ADAPTIVE = {'mdpi': 108, 'hdpi': 162, 'xhdpi': 216, 'xxhdpi': 324, 'xxxhdpi': 432}

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-icons.py — edit the source artwork, not this. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
"""

# (path, bold face index, regular face index). Face indexes matter: picking
# blind gave the tagline an italic face, because Futura.ttc's index 1 is
# Medium *Italic*.
FONT_CANDIDATES = [
    ('/System/Library/Fonts/Avenir Next.ttc', 2, 7),      # Demi Bold / Regular
    ('/System/Library/Fonts/HelveticaNeue.ttc', 1, 0),
    ('/System/Library/Fonts/Supplemental/Futura.ttc', 2, 0),
    ('/Library/Fonts/Arial.ttf', 0, 0),
]


def load_font(size, bold=False):
    for path, bold_ix, regular_ix in FONT_CANDIDATES:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size, index=bold_ix if bold else regular_ix)
            except OSError:
                continue
    return ImageFont.load_default()


def fitted_font(text, size, max_width, bold=False):
    """Largest font at or below `size` whose `text` fits `max_width`."""
    while size > 8:
        font = load_font(size, bold=bold)
        if font.getbbox(text)[2] <= max_width:
            return font
        size -= 2
    return load_font(size, bold=bold)


def square_source(path):
    im = ImageOps.exif_transpose(Image.open(path)).convert('RGB')
    if im.width != im.height:
        side = min(im.width, im.height)
        left, top = (im.width - side) // 2, (im.height - side) // 2
        im = im.crop((left, top, left + side, top + side))
    return im


def resized(src, size):
    im = src.resize((size, size), Image.LANCZOS)
    # The artwork is fine neon line work, which Lanczos turns to mush below
    # ~120px. A mild unsharp measurably restores the swirl arcs and the mask
    # outlines at 60–120px (compared side by side before choosing these
    # numbers); larger sizes don't need it and only pick up ringing.
    if size <= 180:
        im = im.filter(ImageFilter.UnsharpMask(radius=1.0, percent=60, threshold=1))
    return im


def write(im, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path)
    print(f'  {os.path.relpath(path, ROOT)}  {im.width}x{im.height} {im.mode}')


def gen_ios(src):
    print('▶ iOS')
    out = os.path.join(ROOT, 'ios/Runner/Assets.xcassets/AppIcon.appiconset')
    for name, size in sorted(IOS_ICONS.items(), key=lambda kv: kv[1]):
        write(resized(src, size), os.path.join(out, name))

    # Launch screen: the storyboard centres this over a solid colour, so the
    # image itself keeps a transparent surround and stays modest in size.
    launch = os.path.join(ROOT, 'ios/Runner/Assets.xcassets/LaunchImage.imageset')
    for suffix, size in (('', 160), ('@2x', 320), ('@3x', 480)):
        art = resized(src, size).convert('RGBA')
        art.putalpha(circle_alpha(size, feather_from=0.44, feather_to=0.50))
        write(art, os.path.join(launch, f'LaunchImage{suffix}.png'))


def rounded_mask(size, radius):
    mask = Image.new('L', (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size - 1, size - 1],
                                           radius=radius, fill=255)
    return mask


def gen_macos(src):
    print('▶ macOS')
    out = os.path.join(ROOT, 'macos/Runner/Assets.xcassets/AppIcon.appiconset')
    for size in MACOS_ICONS:
        body = max(1, round(size * 824 / 1024))          # Apple's icon grid
        radius = max(1, round(body * 185.4 / 824))
        art = resized(src, body).convert('RGBA')
        art.putalpha(rounded_mask(body, radius))
        canvas = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        offset = (size - body) // 2
        canvas.alpha_composite(art, (offset, offset))
        write(canvas, os.path.join(out, f'app_icon_{size}.png'))


def circle_alpha(size, feather_from=0.44, feather_to=0.50):
    """Alpha mask: opaque inside `feather_from`, transparent past `feather_to`.

    Drawn oversampled then downscaled — a plain ellipse gives a hard,
    aliased rim at launcher sizes.
    """
    scale = 4
    big = size * scale
    mask = Image.new('L', (big, big), 0)
    draw = ImageDraw.Draw(mask)
    outer = big * feather_to
    inner = big * feather_from
    draw.ellipse([big / 2 - outer, big / 2 - outer, big / 2 + outer, big / 2 + outer], fill=0)
    draw.ellipse([big / 2 - inner, big / 2 - inner, big / 2 + inner, big / 2 + inner], fill=255)
    mask = mask.resize((size, size), Image.LANCZOS)
    blur = max(1, round(size * (feather_to - feather_from) * 0.9))
    return mask.filter(ImageFilter.GaussianBlur(blur))


def gen_android(src):
    print('▶ Android')
    res = os.path.join(ROOT, 'android/app/src/main/res')
    for density, size in ANDROID_LEGACY.items():
        art = resized(src, size)
        write(art, os.path.join(res, f'mipmap-{density}/ic_launcher.png'))
        rnd = art.convert('RGBA')
        rnd.putalpha(circle_alpha(size, feather_from=0.485, feather_to=0.50))
        write(rnd, os.path.join(res, f'mipmap-{density}/ic_launcher_round.png'))

    for density, size in ANDROID_ADAPTIVE.items():
        # Background: the artwork's own gradient, blurred past recognition so
        # the corners the mask may reveal still read as part of the icon.
        bg = resized(src, size).filter(ImageFilter.GaussianBlur(size * 0.18))
        write(bg.convert('RGBA'), os.path.join(res, f'mipmap-{density}/ic_launcher_background.png'))

        # Foreground: the art scaled so its circular composition just fits the
        # 72dp safe zone, feathered so no square edge survives any mask shape.
        art_size = max(1, round(size * (72 / 108) / ART_EXTENT))
        art = resized(src, art_size).convert('RGBA')
        art.putalpha(circle_alpha(art_size, feather_from=0.44, feather_to=0.50))
        fg = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        fg.alpha_composite(art, ((size - art_size) // 2, (size - art_size) // 2))
        write(fg, os.path.join(res, f'mipmap-{density}/ic_launcher_foreground.png'))

    for name in ('ic_launcher.xml', 'ic_launcher_round.xml'):
        path = os.path.join(res, 'mipmap-anydpi-v26', name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w') as fh:
            fh.write(ADAPTIVE_XML)
        print(f'  {os.path.relpath(path, ROOT)}')


def corner_gradient(src, w, h):
    """A smooth gradient built from the artwork's four corner colours."""
    patch = max(8, src.width // 12)
    corners = [
        src.crop((0, 0, patch, patch)),
        src.crop((src.width - patch, 0, src.width, patch)),
        src.crop((0, src.height - patch, patch, src.height)),
        src.crop((src.width - patch, src.height - patch, src.width, src.height)),
    ]
    seed = Image.new('RGB', (2, 2))
    seed.putdata([c.resize((1, 1), Image.LANCZOS).getpixel((0, 0)) for c in corners])
    return seed.resize((w, h), Image.BICUBIC)


def gen_play(src):
    print('▶ Play store')
    out = os.path.join(ROOT, 'fastlane/metadata/android/en-US/images')
    write(resized(src, 512), os.path.join(out, 'icon.png'))       # RGB: no alpha

    w, h = 1024, 500
    # Background: a bilinear gradient between the artwork's own corner colours.
    # (Blurring the artwork itself was the first attempt and went muddy — its
    # centre is white and orange line work, which averages to grey.)
    canvas = corner_gradient(src, w, h).convert('RGBA')
    # Mild scrim on the text side; the top-right corner is the palette's
    # brightest cyan and white text needs the contrast.
    scrim = Image.new('L', (w, h))
    scrim_draw = ImageDraw.Draw(scrim)
    for x in range(w):
        scrim_draw.line([(x, 0), (x, h)], fill=int(70 * min(1.0, max(0.0, (x - 300) / 420))))
    canvas.paste(Image.new('RGBA', (w, h), (6, 30, 44, 255)), (0, 0), scrim)

    icon_size = 340
    icon_x, icon_y = 60, (h - icon_size) // 2
    icon = resized(src, icon_size).convert('RGBA')
    icon.putalpha(circle_alpha(icon_size, feather_from=0.455, feather_to=0.50))
    glow = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    glow.alpha_composite(icon, (icon_x, icon_y))
    canvas.alpha_composite(glow.filter(ImageFilter.GaussianBlur(28)))
    canvas.alpha_composite(icon, (icon_x, icon_y))

    text_x = icon_x + icon_size + 60
    avail = w - text_x - 56
    draw = ImageDraw.Draw(canvas)
    title = fitted_font('CastCircle', 88, avail, bold=True)
    tagline = fitted_font('Learn your lines. Rehearse anywhere.', 34, avail)
    draw.text((text_x, 186), 'CastCircle', font=title, fill=(255, 255, 255))
    draw.text((text_x + 3, 300), 'Learn your lines. Rehearse anywhere.',
              font=tagline, fill=(206, 230, 241))
    write(canvas.convert('RGB'), os.path.join(out, 'featureGraphic.png'))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default='assets/castcircleicon.jpeg')
    args = ap.parse_args()

    path = args.src if os.path.isabs(args.src) else os.path.join(ROOT, args.src)
    if not os.path.exists(path):
        sys.exit(f'✗ source artwork not found: {path}')
    src = square_source(path)
    print(f'▶ source {os.path.relpath(path, ROOT)}  {src.width}x{src.height}\n')

    gen_ios(src)
    gen_macos(src)
    gen_android(src)
    gen_play(src)
    print('\n✓ icons regenerated. Rebuild to see them on device '
          '(Android needs a reinstall — launchers cache icons).')


if __name__ == '__main__':
    main()
